<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRx5tkzt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRx5tkzt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRx5tkzt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRx5tkzt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRx5tkzt\appProdProjectContainer(array(
    'container.build_hash' => 'Rx5tkzt',
    'container.build_id' => '075cfc65',
    'container.build_time' => 1542881496,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRx5tkzt');
